apiVersion: v1
kind: Service
metadata:
  name: ms-a
spec:
  selector:
    app: tutum
  ports:
    - port: 9001
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutum
spec:
  selector:
    matchLabels:
      app: tutum
  template:
    metadata:
      labels:
        app: tutum
    spec:
      containers:
        - name: tutum
          image: karthequian/helloworld
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
