apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
    - name: myapp
      image: postgres:latest
      env:
        - name: SECRET_PASSWORD_POSTGRESS
          valueFrom:
            secretKeyRef:
              name: eng-secret
              key: POSTGRES_PASSWORD
